spring:
  application:
    name: zuul-gateway
server:
  port: 8085
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
zuul:
  routes:
    client:
      path: /client/**
      serviceId: eureka-client
    ribbon:
      path: /feign/**
      serviceId: feign-comsumer
